name: text_enroll_md
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - pytorch-cuda=12.1
  - scipy=1.12.0
  - scikit-learn=1.5.1
  - matplotlib=
  - torchmetrics=1.4.0.post0
  - pip:
    - pyyaml-include==1.3
    - soundfile==0.12.1
    - tensorboard
    - pypinyin
    - git+https://github.com/openai/whisper.git
